// Frontend data layer.
// Remote-first: talks to Vercel serverless /api/* backed by MongoDB.
// Offline/dev fallback: localStorage mock with the SAME rules
// (username chosen by user, password generated by system, changeable later)
// so `npm run dev` and the PWA offline shell keep working without env vars.

import { PLANS, planById } from "./store";

const TOKEN_KEY = "p2p_token_v1";
const CACHE_TXNS = "p2p_cache_txns_v1";
const CACHE_NOTIFS = "p2p_cache_notifs_v1";
const CACHE_USER = "p2p_cache_user_v1";

export const getToken = () => localStorage.getItem(TOKEN_KEY);
export const setToken = (t) => (t ? localStorage.setItem(TOKEN_KEY, t) : localStorage.removeItem(TOKEN_KEY));

let remoteOk = null;
export async function remoteAvailable() {
  if (remoteOk !== null) return remoteOk;
  try {
    const r = await fetch("/api/health", { cache: "no-store" });
    const j = await r.json();
    remoteOk = r.ok && j.mongo;
  } catch {
    remoteOk = false;
  }
  return remoteOk;
}

async function call(path, { method = "GET", body } = {}) {
  const headers = { "Content-Type": "application/json" };
  const t = getToken();
  if (t) headers.Authorization = `Bearer ${t}`;
  let r;
  try {
    r = await fetch(path, {
      method,
      headers,
      body: body ? JSON.stringify(body) : undefined,
    });
  } catch (e) {
    throw friendlyError(e);
  }
  let j = {};
  try { j = await r.json(); } catch { /* empty */ }
  if (!r.ok) throw friendlyError(new Error(j.error || `Request failed (${r.status})`));
  return j;
}

// Never surface backend internals (env names, drivers, network jargon) in UI toasts.
function friendlyError(err) {
  const msg = String(err?.message || err || "");
  if (/is not set\.|MongoServer|Mongo_|E11000|ECONN|ENOTFOUND|timed out|timing out/i.test(msg))
    return new Error("Service is having trouble right now. Please try again in a moment.");
  if (/failed to fetch|networkerror|network request failed|load failed|fetch failed/i.test(msg))
    return new Error("You're offline or can't reach the service. Check your connection and retry.");
  return err instanceof Error ? err : new Error(msg || "Something went wrong. Please try again.");
}

const cache = {
  read(k, f) {
    try { const v = localStorage.getItem(k); return v ? JSON.parse(v) : f; } catch { return f; }
  },
  write(k, v) { try { localStorage.setItem(k, JSON.stringify(v)); } catch {} },
};

/* ---------------- local offline fallback (same product rules) ---------------- */
const LK = { users: "p2p_users_v1", session: "p2p_local_user_v1", txns: "p2p_txns_v1", notifs: "p2p_notifs_v1", offers: "p2p_offers_v1", schemes: "p2p_schemes_v1", members: "p2p_members_v1", coinlogs: "p2p_coinlogs_v1" };
const DAY_MS = 86400000;
const MAX_ACCRUE_DAYS = 7;
function localAccrual(m, dailyCoins, nowMs) {
  const days = Math.max(0, Math.min(Math.floor((nowMs - new Date(m.lastSettledAt).getTime()) / DAY_MS), MAX_ACCRUE_DAYS));
  return { days, credit: days * dailyCoins };
}
const lread = (k, f) => cache.read(k, f);
const lwrite = (k, v) => cache.write(k, v);
const uid = (p = "id") => `${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
const ALPH = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%";
export function localGeneratePassword(n = 12) {
  const a = new Uint8Array(n);
  crypto.getRandomValues(a);
  return Array.from(a, (b) => ALPH[b % ALPH.length]).join("");
}
const lhash = (pw) => `dev-demo::${btoa(unescape(encodeURIComponent("salt::" + pw)))}`;

function seedLocal() {
  if (!localStorage.getItem(LK.users)) {
    const now = new Date().toISOString();
    lwrite(LK.users, [
      { id: "u_alice", username: "alice", passwordHash: lhash("Alice-Dev-01!"), wallet: "TAl1c3ExAmPleTru5tW4lletAddr355001", plan: "bronze", role: "member", blocked: false, createdAt: now },
      { id: "u_bob", username: "bob", passwordHash: lhash("Bob-Dev-02!"), wallet: "TB0bExAmpLeTrustWallEt9ddr771200", plan: "bronze", role: "member", blocked: false, createdAt: now },
      { id: "u_carol", username: "carol", passwordHash: lhash("Carol-Dev-03!"), wallet: "TCar0lD3moTrustWalletAddr990021", plan: "silver", role: "member", blocked: false, createdAt: now },
      { id: "u_admin", username: "admin", passwordHash: lhash("Admin-Dev-00!"), wallet: "TAdminCircleLedgerWallet000000001", plan: null, role: "admin", blocked: false, createdAt: now },
    ]);
  }
  if (!localStorage.getItem(LK.txns)) lwrite(LK.txns, []);
  if (!localStorage.getItem(LK.notifs)) lwrite(LK.notifs, []);
  if (!localStorage.getItem(LK.offers)) lwrite(LK.offers, []);
  if (!localStorage.getItem(LK.schemes)) lwrite(LK.schemes, []);
  if (!localStorage.getItem(LK.members)) lwrite(LK.members, []);
  if (!localStorage.getItem(LK.coinlogs)) lwrite(LK.coinlogs, []);
  // migrate older seeds: ensure admin exists + role/blocked flags present
  const seeded = lread(LK.users, []);
  let touched = false;
  const withFlags = seeded.map((u) => {
    const n = { role: "member", blocked: false, ...u };
    if (n.role !== u.role || n.blocked !== u.blocked) touched = true;
    return n;
  });
  if (!withFlags.some((u) => u.username.toLowerCase() === "admin")) {
    withFlags.push({ id: "u_admin", username: "admin", passwordHash: lhash("Admin-Dev-00!"), wallet: "TAdminCircleLedgerWallet000000001", plan: null, role: "admin", blocked: false, createdAt: new Date().toISOString() });
    touched = true;
  }
  if (touched) lwrite(LK.users, withFlags);
}
export const LOCAL_DEMO_CREDS = [
  { username: "alice", password: "Alice-Dev-01!" },
  { username: "bob", password: "Bob-Dev-02!" },
  { username: "carol", password: "Carol-Dev-03!" },
  { username: "admin", password: "Admin-Dev-00!" },
];

const local = {
  signup({ username, wallet }) {
    seedLocal();
    username = String(username || "").trim();
    wallet = String(wallet || "").trim();
    if (username.length < 3) throw new Error("Username must be at least 3 characters.");
    if (!/^[a-zA-Z0-9_.-]+$/.test(username)) throw new Error("Username may only contain letters, numbers, _, . or -.");
    if (username.toLowerCase() === "admin") throw new Error("That username is reserved. Pick another one.");
    if (wallet.length < 10) throw new Error("Paste your public Trust Wallet address text string (min 10 chars).");
    const users = lread(LK.users, []);
    if (users.some((u) => u.username.toLowerCase() === username.toLowerCase()))
      throw new Error("That username is already taken. Pick a unique username.");
    if (users.some((u) => u.wallet === wallet))
      throw new Error("That wallet text is already registered to another member.");
    const generatedPassword = localGeneratePassword(12);
    const user = { id: uid("u"), username, passwordHash: lhash(generatedPassword), wallet, plan: null, createdAt: new Date().toISOString() };
    users.push(user);
    lwrite(LK.users, users);
    lwrite(LK.session, { userId: user.id });
    return { user: strip(user), generatedPassword };
  },
  login({ username, password }) {
    seedLocal();
    const users = lread(LK.users, []);
    const u = users.find((x) => x.username.toLowerCase() === String(username || "").trim().toLowerCase());
    if (!u || u.passwordHash !== lhash(String(password || ""))) throw new Error("Invalid username or password.");
    if (u.blocked) throw new Error("This account has been blocked. Contact support.");
    lwrite(LK.session, { userId: u.id });
    return { user: strip(u) };
  },
  me() {
    seedLocal();
    const s = lread(LK.session, null);
    if (!s) return null;
    const u = lread(LK.users, []).find((x) => x.id === s.userId);
    return u ? strip(u) : null;
  },
  changePassword({ currentPassword, newPassword }) {
    const s = lread(LK.session, null);
    const users = lread(LK.users, []);
    const u = users.find((x) => x.id === s?.userId);
    if (!u) throw new Error("Not authenticated.");
    if (u.passwordHash !== lhash(String(currentPassword || ""))) throw new Error("Current password is incorrect.");
    if (String(newPassword || "").length < 8) throw new Error("New password must be at least 8 characters.");
    u.passwordHash = lhash(String(newPassword));
    lwrite(LK.users, users);
    return { ok: true };
  },
  updateProfile(patch) {
    const s = lread(LK.session, null);
    const users = lread(LK.users, []);
    if (patch.wallet) {
      const clash = users.find((u) => u.wallet === String(patch.wallet).trim() && u.id !== s?.userId);
      if (clash) throw new Error("That wallet text is already registered to another member.");
    }
    const next = users.map((u) => (u.id === s?.userId ? { ...u, ...patch } : u));
    lwrite(LK.users, next);
    return strip(next.find((u) => u.id === s?.userId));
  },
  lookupPartner({ wallet }) {
    seedLocal();
    const wall = String(wallet || "").trim();
    if (wall.length < 10) throw new Error("Paste your partner's full wallet text first.");
    const s = lread(LK.session, null);
    const users = lread(LK.users, []);
    const target = users.find((u) => u.wallet === wall);
    if (!target) throw new Error("No member found with that wallet text. Check for extra spaces or ask your partner to re-send it.");
    if (target.id === s?.userId) throw new Error("That's your own wallet text — paste your partner's instead.");
    const plan = planById(target.plan);
    return { username: target.username, plan: target.plan || null, planName: plan ? plan.name : null, wallet: target.wallet };
  },
  deposit({ planId, targetWallet, offerId }) {
    const plan = planById(planId);
    if (!plan) throw new Error("Select a valid tier first.");
    const wall = String(targetWallet || "").trim();
    if (wall.length < 10) throw new Error("Paste your partner's wallet text first.");
    const s = lread(LK.session, null);
    const users = lread(LK.users, []);
    const sender = users.find((u) => u.id === s?.userId);
    if (!sender) throw new Error("Session expired. Please log in again.");
    if (sender.plan !== planId) {
      sender.plan = planId;
      lwrite(LK.users, users);
    }
    const target = users.find((u) => u.wallet === wall);
    if (!target) throw new Error("No member found with that wallet text. Check for extra spaces or ask your partner to re-send it.");
    if (target.id === sender.id) throw new Error("That's your own wallet text — paste your partner's instead.");
    let schemeId = null, coinAmount = 0, linkedOfferId = null, schemeName = null;
    if (offerId) {
      const offer = lread(LK.offers, []).find((o) => o.id === offerId);
      if (!offer || offer.status !== "open") throw new Error("That lot is no longer open.");
      if (offer.userId !== target.id) throw new Error("That wallet doesn't belong to the lot poster — double-check the address.");
      if (offer.planId !== plan.id) throw new Error("Tier mismatch — pick the tier shown on the lot.");
      linkedOfferId = offer.id;
      if (lread(LK.txns, []).some((t) => t.offerId === linkedOfferId && t.senderId === sender.id && t.status === "awaiting_confirmation"))
        throw new Error("You already have a pending request on this lot — wait for it to complete first.");
      if (offer.schemeId) {
        const membership = lread(LK.members, []).find((m) => m.schemeId === offer.schemeId && m.userId === sender.id);
        if (!membership) throw new Error("Join that coin scheme first — this lot is priced in its coins.");
        if (membership.balance < offer.coinAmount)
          throw new Error(`You hold ${membership.balance} ${offer.schemeName} coins but this lot costs ${offer.coinAmount}. Collect your daily coins first.`);
        schemeId = offer.schemeId;
        schemeName = offer.schemeName;
        coinAmount = offer.coinAmount;
      }
    }
    const txn = {
      id: uid("txn"), senderId: sender.id, senderUsername: sender.username,
      targetId: target.id, targetUsername: target.username, targetWalletSnapshot: target.wallet,
      planId: plan.id, planName: plan.name, amount: plan.amount,
      status: "awaiting_confirmation",
      schemeId, schemeName, coinAmount, offerId: linkedOfferId,
      copyLoggedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(), completedAt: null, verifiedAmount: null,
    };
    const txns = lread(LK.txns, []);
    lwrite(LK.txns, [txn, ...txns]);
    const notifs = lread(LK.notifs, []);
    lwrite(LK.notifs, [{
      id: uid("notif"), userId: target.id, txnId: txn.id,
      text: schemeId
        ? `User ${sender.username} sent you a pairing request for the ${plan.name} tier (${coinAmount} ${schemeName} coins).`
        : `User ${sender.username} sent you a pairing request for the ${plan.name} tier.`,
      read: false, createdAt: new Date().toISOString(),
    }, ...notifs]);
    return { txn, target: strip(target) };
  },
  txns() {
    const me = local.me();
    if (!me) return [];
    return lread(LK.txns, []).filter((t) => t.senderId === me.id || t.targetId === me.id);
  },
  notifs() {
    const me = local.me();
    if (!me) return [];
    return lread(LK.notifs, []).filter((n) => n.userId === me.id);
  },
  markRead(notifId, read = true) {
    lwrite(LK.notifs, lread(LK.notifs, []).map((n) => (n.id === notifId ? { ...n, read } : n)));
  },
  markAllRead() {
    const me = local.me();
    lwrite(LK.notifs, lread(LK.notifs, []).map((n) => (n.userId === me?.id ? { ...n, read: true } : n)));
  },
  ack({ txnId, verifiedAmount }) {
    const me = local.me();
    const txns = lread(LK.txns, []);
    const txn = txns.find((t) => t.id === txnId);
    if (!txn) throw new Error("Transaction not found.");
    if (txn.targetId !== me?.id) throw new Error("Only the Target User can acknowledge this entry.");
    if (txn.status === "completed") throw new Error("This entry is already completed.");
    const amt = Number(verifiedAmount);
    if (!amt || amt <= 0) throw new Error("Select the exact amount you verified receiving.");
    if (txn.schemeId && txn.coinAmount > 0) {
      const members = lread(LK.members, []);
      const buyer = members.find((m) => m.schemeId === txn.schemeId && m.userId === txn.senderId);
      const seller = members.find((m) => m.schemeId === txn.schemeId && m.userId === txn.targetId);
      if (!buyer || buyer.balance < txn.coinAmount)
        throw new Error(`The buyer no longer holds the ${txn.coinAmount} ${txn.schemeName} coins — ask them to collect their daily coins first.`);
      if (!seller) throw new Error("The seller is no longer in that coin scheme.");
      buyer.balance -= txn.coinAmount;
      seller.balance += txn.coinAmount;
      lwrite(LK.members, members);
      const logs = lread(LK.coinlogs, []);
      const now2 = new Date().toISOString();
      lwrite(LK.coinlogs, [
        { id: uid("log"), userId: txn.senderId, schemeId: txn.schemeId, schemeName: txn.schemeName, kind: "spend", amount: -txn.coinAmount, balanceAfter: buyer.balance, ref: txn.id, at: now2 },
        { id: uid("log"), userId: txn.targetId, schemeId: txn.schemeId, schemeName: txn.schemeName, kind: "earn", amount: txn.coinAmount, balanceAfter: seller.balance, ref: txn.id, at: now2 },
        ...logs,
      ]);
      if (txn.offerId) {
        const offers = lread(LK.offers, []);
        const offer = offers.find((o) => o.id === txn.offerId);
        if (offer) {
          Object.assign(offer, { status: "closed", closedAt: now2 });
          lwrite(LK.offers, offers);
        }
      }
    }
    Object.assign(txn, { status: "completed", verifiedAmount: amt, completedAt: new Date().toISOString() });
    lwrite(LK.txns, txns);
    const notifs = lread(LK.notifs, []);
    lwrite(LK.notifs, [{
      id: uid("notif"), userId: txn.senderId, txnId: txn.id,
      text: txn.schemeId
        ? `User ${txn.targetUsername} acknowledged & confirmed your ${txn.planName} entry (${txn.coinAmount} ${txn.schemeName} coins moved). Status: Completed.`
        : `User ${txn.targetUsername} acknowledged & confirmed your ${txn.planName} entry (${amt}). Status: Completed.`,
      read: false, createdAt: new Date().toISOString(),
    }, ...notifs]);
    return txn;
  },
  _requireAdmin() {
    seedLocal();
    const s = lread(LK.session, null);
    const me = lread(LK.users, []).find((x) => x.id === s?.userId);
    if (!me || (me.role !== "admin" && me.username.toLowerCase() !== "admin")) throw new Error("Admins only.");
    return me;
  },
  adminUsers() {
    this._requireAdmin();
    return lread(LK.users, []).map(strip);
  },
  adminTxns() {
    this._requireAdmin();
    return lread(LK.txns, []);
  },
  adminComplete({ txnId }) {
    this._requireAdmin();
    const txns = lread(LK.txns, []);
    const txn = txns.find((t) => t.id === txnId);
    if (!txn) throw new Error("Record not found.");
    if (txn.status === "completed") throw new Error("This record is already completed.");
    let coinNote = "";
    if (txn.schemeId && txn.coinAmount > 0) {
      const members = lread(LK.members, []);
      const buyer = members.find((m) => m.schemeId === txn.schemeId && m.userId === txn.senderId);
      const seller = members.find((m) => m.schemeId === txn.schemeId && m.userId === txn.targetId);
      if (buyer && seller && buyer.balance >= txn.coinAmount) {
        buyer.balance -= txn.coinAmount;
        seller.balance += txn.coinAmount;
        lwrite(LK.members, members);
        const logs = lread(LK.coinlogs, []);
        const now2 = new Date().toISOString();
        lwrite(LK.coinlogs, [
          { id: uid("log"), userId: txn.senderId, schemeId: txn.schemeId, schemeName: txn.schemeName, kind: "spend", amount: -txn.coinAmount, balanceAfter: buyer.balance, ref: txn.id, at: now2 },
          { id: uid("log"), userId: txn.targetId, schemeId: txn.schemeId, schemeName: txn.schemeName, kind: "earn", amount: txn.coinAmount, balanceAfter: seller.balance, ref: txn.id, at: now2 },
          ...logs,
        ]);
      } else {
        coinNote = " Coin settlement is pending — the buyer no longer holds enough coins.";
      }
      if (txn.offerId) {
        const offers = lread(LK.offers, []);
        const offer = offers.find((o) => o.id === txn.offerId);
        if (offer) {
          Object.assign(offer, { status: "closed", closedAt: new Date().toISOString() });
          lwrite(LK.offers, offers);
        }
      }
    }
    Object.assign(txn, { status: "completed", verifiedAmount: txn.amount, completedAt: new Date().toISOString() });
    lwrite(LK.txns, txns);
    const note = `An admin marked your ${txn.planName} record (@${txn.senderUsername} ↔ @${txn.targetUsername}) as Completed.${coinNote}`;
    const notifs = lread(LK.notifs, []);
    lwrite(LK.notifs, [
      { id: uid("notif"), userId: txn.senderId, txnId: txn.id, text: note, read: false, createdAt: new Date().toISOString() },
      { id: uid("notif"), userId: txn.targetId, txnId: txn.id, text: note, read: false, createdAt: new Date().toISOString() },
      ...notifs,
    ]);
    return txn;
  },
  adminBlock({ userId, blocked }) {
    this._requireAdmin();
    const users = lread(LK.users, []);
    const target = users.find((u) => u.id === userId);
    if (!target) throw new Error("User not found.");
    if (target.role === "admin" || target.username.toLowerCase() === "admin") throw new Error("Admin accounts can't be blocked.");
    target.blocked = !!blocked;
    lwrite(LK.users, users);
    return { ok: true };
  },
  offers() {
    seedLocal();
    const s = lread(LK.session, null);
    return lread(LK.offers, []).filter((o) => o.status === "open" || o.userId === s?.userId);
  },
  offerCreate({ side, planId, note, schemeId }) {
    seedLocal();
    if (!["sell", "buy"].includes(side)) throw new Error("Choose whether this lot is open to sell or open to buy.");
    const plan = planById(planId);
    if (!plan) throw new Error("Select a valid tier for this lot.");
    const s = lread(LK.session, null);
    const me = lread(LK.users, []).find((x) => x.id === s?.userId);
    if (!me) throw new Error("Not authenticated.");
    let coinSchemeId = null, schemeName = null, coinAmount = 0;
    if (schemeId) {
      const scheme = lread(LK.schemes, []).find((x) => x.id === schemeId && x.status === "active");
      if (!scheme) throw new Error("That coin scheme is no longer active.");
      const membership = lread(LK.members, []).find((m) => m.schemeId === scheme.id && m.userId === me.id);
      if (!membership) throw new Error("Join that coin scheme first — then price lots in its coins.");
      coinSchemeId = scheme.id;
      schemeName = scheme.name;
      coinAmount = plan.amount;
    }
    const offer = {
      id: uid("offer"), userId: me.id, username: me.username,
      side, planId: plan.id, planName: plan.name, amount: plan.amount,
      schemeId: coinSchemeId, schemeName, coinAmount,
      note: String(note || "").trim().slice(0, 200), status: "open",
      createdAt: new Date().toISOString(), closedAt: null,
    };
    lwrite(LK.offers, [offer, ...lread(LK.offers, [])]);
    return { offer };
  },
  offerClose({ offerId }) {
    const s = lread(LK.session, null);
    const offers = lread(LK.offers, []);
    const offer = offers.find((o) => o.id === offerId);
    if (!offer) throw new Error("Lot not found.");
    if (offer.userId !== s?.userId) throw new Error("Only the poster can close this lot.");
    Object.assign(offer, { status: "closed", closedAt: new Date().toISOString() });
    lwrite(LK.offers, offers);
    return { ok: true };
  },
  offerInterest({ offerId }) {
    seedLocal();
    const s = lread(LK.session, null);
    const me = lread(LK.users, []).find((x) => x.id === s?.userId);
    if (!me) throw new Error("Not authenticated.");
    const offers = lread(LK.offers, []);
    const offer = offers.find((o) => o.id === offerId);
    if (!offer || offer.status !== "open") throw new Error("That lot is no longer open.");
    if (offer.userId === me.id) throw new Error("That's your own lot.");
    if ((offer.interested || []).includes(me.id)) throw new Error("You've already shown interest in this lot — the poster has been notified.");
    offer.interested = [...(offer.interested || []), me.id];
    lwrite(LK.offers, offers);
    const notifs = lread(LK.notifs, []);
    lwrite(LK.notifs, [{
      id: uid("notif"), userId: offer.userId, txnId: null,
      text: `User ${me.username} is interested in your lot (${offer.side === "sell" ? "open to sell" : "open to buy"} · ${offer.planName} $${offer.amount}). Share your wallet text with them outside the app to pair.`,
      read: false, createdAt: new Date().toISOString(),
    }, ...notifs]);
    return { ok: true };
  },
  schemes() {
    seedLocal();
    const s = lread(LK.session, null);
    const members = lread(LK.members, []);
    const mine = new Set(members.filter((m) => m.userId === s?.userId).map((m) => m.schemeId));
    return lread(LK.schemes, [])
      .filter((x) => x.status === "active")
      .map((x) => ({
        id: x.id, name: x.name, dailyCoins: x.dailyCoins,
        ownerId: x.ownerId, ownerUsername: x.ownerUsername,
        members: members.filter((m) => m.schemeId === x.id).length,
        mine: mine.has(x.id), createdAt: x.createdAt,
      }));
  },
  schemeCreate({ name, dailyCoins }) {
    seedLocal();
    const cleanName = String(name || "").trim().slice(0, 40);
    if (cleanName.length < 3) throw new Error("Give your scheme a name (3–40 characters).");
    const rate = Math.floor(Number(dailyCoins));
    if (!rate || rate < 1 || rate > 1000) throw new Error("Daily coins must be between 1 and 1000.");
    const s = lread(LK.session, null);
    const me = lread(LK.users, []).find((x) => x.id === s?.userId);
    if (!me) throw new Error("Not authenticated.");
    const now = new Date().toISOString();
    const scheme = {
      id: uid("scheme"), ownerId: me.id, ownerUsername: me.username,
      name: cleanName, dailyCoins: rate, status: "active", createdAt: now,
    };
    lwrite(LK.schemes, [scheme, ...lread(LK.schemes, [])]);
    lwrite(LK.members, [
      { id: uid("mem"), schemeId: scheme.id, userId: me.id, balance: 0, lastSettledAt: now, joinedAt: now },
      ...lread(LK.members, []),
    ]);
    return { scheme };
  },
  schemeJoin({ schemeId }) {
    seedLocal();
    const s = lread(LK.session, null);
    const me = lread(LK.users, []).find((x) => x.id === s?.userId);
    if (!me) throw new Error("Not authenticated.");
    const scheme = lread(LK.schemes, []).find((x) => x.id === schemeId && x.status === "active");
    if (!scheme) throw new Error("That scheme is no longer active.");
    const members = lread(LK.members, []);
    if (members.some((m) => m.schemeId === scheme.id && m.userId === me.id))
      throw new Error("You're already in this scheme — collect your daily coins.");
    const now = new Date().toISOString();
    lwrite(LK.members, [
      { id: uid("mem"), schemeId: scheme.id, userId: me.id, balance: 0, lastSettledAt: now, joinedAt: now },
      ...members,
    ]);
    return { ok: true };
  },
  schemeLeave({ schemeId }) {
    const s = lread(LK.session, null);
    const members = lread(LK.members, []);
    const idx = members.findIndex((m) => m.schemeId === String(schemeId) && m.userId === s?.userId);
    if (idx < 0) throw new Error("You're not in this scheme.");
    members.splice(idx, 1);
    lwrite(LK.members, members);
    return { ok: true, note: "Unspent coins in this scheme were forfeited." };
  },
  myCoins() {
    seedLocal();
    const s = lread(LK.session, null);
    const schemes = Object.fromEntries(lread(LK.schemes, []).map((x) => [x.id, x]));
    const nowMs = Date.now();
    return lread(LK.members, [])
      .filter((m) => m.userId === s?.userId && schemes[m.schemeId] && schemes[m.schemeId].status === "active")
      .map((m) => {
        const sc = schemes[m.schemeId];
        const { days, credit } = localAccrual(m, sc.dailyCoins, nowMs);
        return {
          schemeId: m.schemeId, schemeName: sc.name, dailyCoins: sc.dailyCoins,
          ownerUsername: sc.ownerUsername, balance: m.balance,
          claimable: credit, claimableDays: days,
        };
      })
      .sort((a, b) => b.balance - a.balance);
  },
  collect({ schemeId }) {
    const s = lread(LK.session, null);
    const members = lread(LK.members, []);
    const m = members.find((x) => x.schemeId === String(schemeId) && x.userId === s?.userId);
    if (!m) throw new Error("Join this scheme first.");
    const scheme = lread(LK.schemes, []).find((x) => x.id === m.schemeId);
    if (!scheme || scheme.status !== "active") throw new Error("That scheme is no longer active.");
    const { days, credit } = localAccrual(m, scheme.dailyCoins, Date.now());
    if (!credit) return { credited: 0, balance: m.balance, message: "Nothing to collect yet — come back tomorrow." };
    m.balance += credit;
    m.lastSettledAt = new Date(new Date(m.lastSettledAt).getTime() + days * DAY_MS).toISOString();
    lwrite(LK.members, members);
    const logs = lread(LK.coinlogs, []);
    lwrite(LK.coinlogs, [
      { id: uid("log"), userId: m.userId, schemeId: m.schemeId, schemeName: scheme.name, kind: "collect", amount: credit, balanceAfter: m.balance, ref: `${days}d`, at: new Date().toISOString() },
      ...logs,
    ]);
    return { credited: credit, balance: m.balance };
  },
  coinHistory() {
    seedLocal();
    const s = lread(LK.session, null);
    return lread(LK.coinlogs, []).filter((l) => l.userId === s?.userId).slice(0, 100);
  },
};
function strip(u) {
  if (!u) return null;
  const { passwordHash, usernameLower, ...rest } = u;
  return rest;
}

/* ---------------- unified public API ---------------- */
async function useRemote() {
  try { return await remoteAvailable(); } catch { return false; }
}

export async function apiSignup({ username, wallet }) {
  if (await useRemote()) {
    const j = await call("/api/auth?action=signup", { method: "POST", body: { username, wallet } });
    setToken(j.token);
    cache.write(CACHE_USER, j.user);
    return j; // { user, generatedPassword, token }
  }
  const j = local.signup({ username, wallet });
  cache.write(CACHE_USER, j.user);
  return j;
}

export async function apiLogin({ username, password }) {
  if (await useRemote()) {
    const j = await call("/api/auth?action=login", { method: "POST", body: { username, password } });
    setToken(j.token);
    cache.write(CACHE_USER, j.user);
    return j;
  }
  const j = local.login({ username, password });
  cache.write(CACHE_USER, j.user);
  return j;
}

export async function apiMe() {
  const cached = cache.read(CACHE_USER, null);
  if (await useRemote()) {
    if (!getToken()) return null;
    try {
      const j = await call("/api/auth?action=me");
      cache.write(CACHE_USER, j.user);
      return j.user;
    } catch {
      return null;
    }
  }
  return local.me() || cached;
}

export async function apiChangePassword({ currentPassword, newPassword }) {
  if (await useRemote()) return call("/api/auth?action=change-password", { method: "POST", body: { currentPassword, newPassword } });
  return local.changePassword({ currentPassword, newPassword });
}

export async function apiUpdateProfile(patch) {
  if (await useRemote()) {
    const j = await call("/api/user", { method: "POST", body: patch });
    cache.write(CACHE_USER, j.user);
    return j.user;
  }
  const u = local.updateProfile(patch);
  cache.write(CACHE_USER, u);
  return u;
}

export async function apiLookupPartner(wallet) {
  if (await useRemote()) return call("/api/pairing?action=lookup", { method: "POST", body: { wallet } });
  return { partner: local.lookupPartner({ wallet }) };
}

export async function apiDeposit(planId, targetWallet, offerId) {
  if (await useRemote()) return call("/api/pairing?action=request", { method: "POST", body: { planId, targetWallet, offerId } });
  return local.deposit({ planId, targetWallet, offerId });
}

export async function apiTxns() {
  if (await useRemote()) {
    try {
      const j = await call("/api/txns");
      cache.write(CACHE_TXNS, j.txns);
      return j.txns;
    } catch { return cache.read(CACHE_TXNS, []); }
  }
  return local.txns();
}

export async function apiNotifs() {
  if (await useRemote()) {
    try {
      const j = await call("/api/notifs");
      cache.write(CACHE_NOTIFS, j.notifs);
      return j.notifs;
    } catch { return cache.read(CACHE_NOTIFS, []); }
  }
  return local.notifs();
}

export async function apiMarkRead(notifId) {
  if (await useRemote()) { try { await call("/api/notifs?action=read", { method: "POST", body: { notifId } }); } catch {} return; }
  local.markRead(notifId, true);
}

export async function apiMarkAllRead() {
  if (await useRemote()) { try { await call("/api/notifs?action=read", { method: "POST", body: { all: true } }); } catch {} return; }
  local.markAllRead();
}

export async function apiAck({ txnId, verifiedAmount }) {
  if (await useRemote()) return call("/api/ack", { method: "POST", body: { txnId, verifiedAmount } });
  return local.ack({ txnId, verifiedAmount });
}

export async function apiAdminUsers() {
  if (await useRemote()) return (await call("/api/admin?action=users")).users;
  return local.adminUsers();
}

export async function apiAdminTxns() {
  if (await useRemote()) return (await call("/api/admin?action=txns")).txns;
  return local.adminTxns();
}

export async function apiAdminComplete(txnId) {
  if (await useRemote()) return call("/api/admin?action=complete", { method: "POST", body: { txnId } });
  return local.adminComplete({ txnId });
}

export async function apiAdminBlock(userId, blocked) {
  if (await useRemote()) return call("/api/admin?action=block", { method: "POST", body: { userId, blocked } });
  return local.adminBlock({ userId, blocked });
}

export async function apiOffers() {
  if (await useRemote()) {
    try {
      const j = await call("/api/pairing?action=offers");
      cache.write("p2p_cache_offers_v1", j.offers);
      return j.offers;
    } catch { return cache.read("p2p_cache_offers_v1", []); }
  }
  return local.offers();
}

export async function apiOfferCreate({ side, planId, note, schemeId }) {
  if (await useRemote()) return call("/api/pairing?action=offer-create", { method: "POST", body: { side, planId, note, schemeId } });
  return local.offerCreate({ side, planId, note, schemeId });
}

export async function apiOfferClose(offerId) {
  if (await useRemote()) return call("/api/pairing?action=offer-close", { method: "POST", body: { offerId } });
  return local.offerClose({ offerId });
}

export async function apiOfferInterest(offerId) {
  if (await useRemote()) return call("/api/pairing?action=offer-interest", { method: "POST", body: { offerId } });
  return local.offerInterest({ offerId });
}

export async function apiSchemes() {
  if (await useRemote()) {
    try {
      const j = await call("/api/pairing?action=schemes");
      cache.write("p2p_cache_schemes_v1", j.schemes);
      return j.schemes;
    } catch { return cache.read("p2p_cache_schemes_v1", []); }
  }
  return local.schemes();
}

export async function apiSchemeCreate({ name, dailyCoins }) {
  if (await useRemote()) return call("/api/pairing?action=scheme-create", { method: "POST", body: { name, dailyCoins } });
  return local.schemeCreate({ name, dailyCoins });
}

export async function apiSchemeJoin(schemeId) {
  if (await useRemote()) return call("/api/pairing?action=scheme-join", { method: "POST", body: { schemeId } });
  return local.schemeJoin({ schemeId });
}

export async function apiSchemeLeave(schemeId) {
  if (await useRemote()) return call("/api/pairing?action=scheme-leave", { method: "POST", body: { schemeId } });
  return local.schemeLeave({ schemeId });
}

export async function apiMyCoins() {
  if (await useRemote()) {
    try {
      const j = await call("/api/pairing?action=my-coins");
      cache.write("p2p_cache_coins_v1", j.coins);
      return j.coins;
    } catch { return cache.read("p2p_cache_coins_v1", []); }
  }
  return local.myCoins();
}

export async function apiCollect(schemeId) {
  if (await useRemote()) return call("/api/pairing?action=collect", { method: "POST", body: { schemeId } });
  return local.collect({ schemeId });
}

export async function apiCoinHistory() {
  if (await useRemote()) {
    try {
      const j = await call("/api/pairing?action=coin-history");
      return j.moves;
    } catch { return []; }
  }
  return local.coinHistory();
}

export function apiLogout() {
  setToken(null);
  localStorage.removeItem(CACHE_USER);
  try { localStorage.removeItem(LK.session); } catch {}
}

export function exportLedgerJSON(txns) {
  const blob = new Blob([JSON.stringify({ exportedAt: new Date().toISOString(), txns }, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "manual-ledger-export.json";
  a.click();
  URL.revokeObjectURL(url);
}

export { PLANS };
