import crypto from "crypto";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import { ObjectId } from "mongodb";
import { getDb } from "./mongo.js";

// Username is chosen by the user. Password is generated by the system.
const ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%";
export function generatePassword(length = 12) {
  const bytes = crypto.randomBytes(length);
  let out = "";
  for (let i = 0; i < length; i++) out += ALPHABET[bytes[i] % ALPHABET.length];
  return out;
}

export async function hashPassword(pw) {
  return bcrypt.hash(pw, 10);
}
export async function verifyPassword(pw, hash) {
  return bcrypt.compare(pw, hash);
}

export function signToken(userId) {
  const secret = process.env.JWT_SECRET;
  if (!secret) throw new Error("JWT_SECRET is not set. Add it in Vercel env vars (and .env locally).");
  return jwt.sign({ sub: String(userId) }, secret, { expiresIn: "30d" });
}

export async function getAuthUser(req) {
  const h = req.headers.authorization || "";
  const token = h.startsWith("Bearer ") ? h.slice(7) : null;
  if (!token) return null;
  try {
    const secret = process.env.JWT_SECRET;
    const payload = jwt.verify(token, secret);
    const db = await getDb();
    const u = await db.collection("users").findOne({ _id: new ObjectId(payload.sub) });
    return u;
  } catch {
    return null;
  }
}
